language: node_js
node_js:
- '0.12'
script:
- npm run ci
deploy:
  provider: npm
  email: rsrichardstevens@googlemail.com
  api_key:
    secure: Jh3P/iF1Bmi3wR2x+Xu1FBKjt5QPfWGcdreNbpxdczstgy0fywqluKO9UJzLOotGA79rp3AdcoyC7V1b68YIR/QX40eo0ptXZ5sjHSIgV/zD9uY9uN7ebNlpPobIwJL9xh21+4mkHrnGYj1NMXmGY6fOZLCq5OeyeFuspymrCEK2xr5sLXILxmathbKp0qJAZQ4ktVQOgm8uF8OyiTBiqaGlaBoykVnMAM8UO220P5KxyOZZzZiekwaOajfYonUSHfV26ap3Q3OpEC3rqoj/xrcLgKYYTiSkbiwongkik6I+N3YRcnsshV6XUX5T4B/AjXTku6xVSjQJL/MpffCUujNeSMldVraEzqrzBJio3m821yZYOM0VhJiCOLLGPAhEUI3G2mwLhlru0DSJYPhXBNTV5v/Lc8adxW10VXl07h3tSLeTmQIpuHFUBlXjXnadGDhY/A179QxSoBFPpIVE+238UXQFkjkYNaLEYMKawgcXaFG30auWUaNDniVpsXMUh4hFyhj1INuSys/BvvpnVSnLUYUFonfRlL00k4poHmqcQmBoR4TptmIZq452xD9qhpYjL+3iz+XYuswoSTRtPRq6IJzeb91aO9toJIdU5aE4tfJyZ7yrzJwOQLnaM95KwILloH9jAMINpJWpaaO3RHDz9KgdbJinnG1taK9EUHY=
  skip_cleanup: true
  on:
    branch: master
