version: 2

defaults: &defaults
  working_directory: ~/metalsmith-react-tpl
  docker:
    - image: circleci/node:10.14.0

jobs:
  initialise:
    <<: *defaults
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Branch and name
          command: |
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_USERNAME}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: npm run ci
      # Install project dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/metalsmith-react-tpl
          paths: .
  deploy:
    <<: *defaults
    steps:
      # Restore dependencies from cache
      - attach_workspace:
          at: ~/metalsmith-react-tpl
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/metalsmith-react-tpl/.npmrc
      - run:
          name: Publish package
          command: npm publish


workflows:
  version: 2
  ssg:
    jobs:
      - initialise
      - deploy:
          requires:
            - initialise
          filters:
            branches:
              only: master